### ISSUE TITLE
Syntax theme not working with Dark theme

### ISSUE THREAD

**Issue by SmartManoj** [StylishThemes/Feature-Override-Styles#9]
* **Browser**: Vivaldi
* **Operating System**:  Win 11
* Version 
Dark 5.1.1
Syntax 2.0.10
* **Link to page with the issue**:  https://stackoverflow.com/questions/41383787/round-down-to-2-decimal-in-python 
* **Screenshot**: 

![image](https://user-images.githubusercontent.com/7231077/163677731-afc98341-6b81-42b8-86c0-e383e0b0ffba.png)
![image](https://user-images.githubusercontent.com/7231077/163677798-704c71da-5857-4294-81eb-36adf87ce1ec.png)

**Comment by the-j0k3r** [comment]
Pehaps an update upstream broke the syntax style, or the SO style is breaking something, I dont use this style anymore, but when I have time Ill look into the syntax theme bit.

Its not a priority for me as I dont really use the site much.

Thanks for report though.

**Comment by the-j0k3r** [comment]
found the issue, a recent update broke syntax themes, was easy fix so, Ill publish soon.
